= README

:toc:

This is a collection of ruby plugins enhancing Asciidoctor to produce (among others) H5P-Plugins. 

== DISCLAIMER
I wrote this collection for my master's thesis and had to remove some of the functionality for this public version as it used a university server; the TableBlock, StemBlock and CodeFrame for the H5P Output relied on this server to upload and link to. Such a server would need to be provided for these to work.  

== Plugins

This is a list of the available plugins

.Currently available Plugins
|===
|Plugin|keyword|website
|Drag the Words|dragtext|https://h5p.org/drag-the-words
|Fill in the Blanks|fillblanks|https://h5p.org/fill-in-the-blanks
|iFrame|iframe|https://h5p.org/iframe-embedder
|Mark The Words|markwords|https://h5p.org/mark-the-words
|MultipleChoice|multi|https://h5p.org/multichoice
|True/False Questions|truefalse|https://h5p.org/true-false
|Text (only inside container)|text|none
|||
|Column|column|https://h5p.org/column
|Quiz (Question Set)|quiz|https://h5p.org/question-set
|===

== Usage & File Structure

All source files go into the src-folder. The toolchain will (via CI/CD or make) create a html file in the root folder as well as a folder containing all h5p files in H5POutput/ for each .adoc file.

If a container plugin is used, all plugins within that container will exist as their own h5p files as well, i.e. for a true/false plugin within a quiz plugin you will get two h5p files as outputs, one for the quiz plugin containing a true/false question and one for the true/false question on its own, both of which can be used independently.

== Syntax

All plugins (with the exception of the two container plugins column and quiz) are created in the source document like this:

....
[keyword]
--
your content goes here
--
....

Please refer to the following section to see how content inside each plugin is styled. Usually stars(*) are used to mark special words for the plugin.

=== Individual Plugins

==== Drag The Words

....
Text inside a dragtext-environment is marked like *this* for words that are draggable
....

==== Fill in The Blanks

....
To mark a word to be left blank for the task, mark it like *this*
....

==== iFrame

....
just put the URL as content
....

==== Mark The Words

....
For this task, students are asked to mark special words. To create a task, mark the words to be highlighted like *this*
....

==== Multiple Choice

....
For this task, you put a question first and end it with a question mark followed by a blank line like this?

- Each option
- is put like this
- *correct options are marked like this*
- *It is possible to have more than one correct answer*
....

==== True/False Question

....
For this task you put a statement first, followed by a line containing either "true" or "false"
true
....

==== Text

....
This plugin simply contains text. It cannot be used as-is but only inside a column-plugin
....

=== Container Blocks

Container blocks serve as a collection of other blocks. The column plugin is able to contain all other plugins, whereas the quiz plugin can contain the question types dragtext, multi, markwords, fillblanks and truefalse.
The usage of container blocks to contain other blocks is demonstrated here:

....
[column]
====
[text]
--
This is a text block within a column block. The column block is initiated and terminated by four "="-signs. What follows is a quiz block containing a multiple choice question. The Quiz-Block is initiated and terminated by five or more "="-signs.
--

[quiz]
=====
[truefalse]
--
This question is part of a (very short) quiz
true
--
=====
====
....

For more examples, feel free to take a look at the h5p-testing.adoc file, which produces a column-plugin containing all other plugins

